### ISSUE TITLE
关于博客抄袭的问题

### ISSUE THREAD

**Issue by CatTail** [dengshenyu/dengshenyu.github.io#1]
你好，发现你的博客 http://www.dengshenyu.com/ 完全抄袭了我的博客（之前）https://cattail.me/ ，样式抄袭还只是小事，但是务必做两件事情

1. 将代码中GA代码修改为你自己的
2. 删除Lab中的描述 http://www.dengshenyu.com/lab/。git-hooks是你的项目么！！！！！！

上述内容已经发送邮件，时间超过一个星期，建议你检查一下邮箱。

**Comment by dengshenyu** [comment]
Hi CatTail, 

很抱歉没有获得你的允许情况下使用你的jekyll主题样式。我最近没上Gmail邮箱查看邮件，没看到您给我发的邮件十分抱歉。

因为我对前端的样式不是很熟悉，所以在搭建博客的过程中找了些已有的jekyll博客来看。您的博客样式简单好看，所以冒昧的拿来用了。

GA的代码我已经删除了，我之前不知道这些是属于你个人的，非常抱歉。

另外Lab中的git-hook我以为是一个开源的repo，所以没有删除，并没有想作为我自己项目的意思。

我希望您能够允许我继续使用您的jekyll样式。谢谢！
